# Generated by Django 3.1.6 on 2021-02-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210212_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='img',
            field=models.ImageField(upload_to='artworks/static/artworks/media'),
        ),
    ]
