# Generated by Django 3.1.6 on 2021-02-15 13:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20210212_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:/work2/maria/maria/media/artworks/static/artworks/media'), upload_to='D:/work2/maria/maria/media/artworks/static/artworks/media'),
        ),
    ]
