# Generated by Django 3.1.6 on 2021-02-24 09:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20210224_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media'), upload_to='media'),
        ),
    ]
