# Generated by Django 3.1.6 on 2021-02-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20210224_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworks',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/static/artworks/media/'),
        ),
    ]
